TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

USERNAME = ""
PASSWORD = ""

TARGET_CLASSES = [
    ("INF1843", "A7"),
    ("INF1943", "A1"),
]

POLL_MIN_SECONDS = 30
POLL_MAX_SECONDS = 60
REMINDER_INTERVAL_SECONDS = 120

REQUEST_TIMEOUT_SECONDS = 30
STATE_FILE = "notify_state.json"
LOG_FILE = "krs_watcher.log"
